server:
  port: 8081
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://8.130.70.247/db1?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 2494088755

api:
  client_id: 'bQFoUxqy22W5c2DTbq5HMsGI'
  client_secret: 'NOty9xqMB2Q6rHZimi5R76YGSOfw2evG'

upload:
  path: /var/img/uploads
