server:
  port: 8081
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 2494088755

mybatis-plus:
  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  path: D:\img
